In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import log_loss

In [2]:
loc = "C:/Users/LAPTOP/Downloads/ChurnData.csv"
telecom_data = pd.read_csv(loc)

In [3]:
telecom_data.sample(5)

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
9,49.0,51.0,27.0,63.0,4.0,19.0,0.0,1.0,0.0,12.85,...,0.0,1.0,1.0,0.0,1.0,2.553,3.248,4.143,2.0,0.0
119,24.0,58.0,30.0,24.0,1.0,5.0,0.0,0.0,0.0,7.65,...,0.0,0.0,0.0,0.0,0.0,2.035,2.773,3.178,1.0,0.0
144,45.0,27.0,3.0,39.0,3.0,2.0,0.0,0.0,0.0,13.45,...,0.0,0.0,0.0,0.0,0.0,2.599,3.240,3.664,2.0,0.0
153,59.0,32.0,9.0,73.0,4.0,5.0,0.0,1.0,0.0,29.20,...,0.0,0.0,1.0,0.0,1.0,3.374,3.068,4.290,2.0,1.0
92,39.0,47.0,1.0,68.0,4.0,10.0,0.0,0.0,0.0,8.30,...,0.0,1.0,0.0,0.0,1.0,2.116,3.240,4.220,2.0,1.0

In [4]:
telecom_data  = telecom_data[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip', 'churn']]
telecom_data['churn'] = telecom_data['churn'].astype(int)
telecom_data

     tenure   age  address  income   ed  employ  equip  churn
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0      1
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0      1
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0      0
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0      0
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0      0
..      ...   ...      ...     ...  ...     ...    ...    ...
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0      0
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0      0
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0      0
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0      1
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0      0

[200 rows x 8 columns]

In [5]:
telecom_data.corr()

,tenure,age,address,income,ed,employ,equip,churn
tenure,1.000000,0.431802,0.456328,0.109383,-0.070503,0.445755,-0.117102,-0.376860
age,0.431802,1.000000,0.746566,0.211275,-0.071509,0.622553,-0.071357,-0.287697
address,0.456328,0.746566,1.000000,0.132807,-0.145550,0.520926,-0.148977,-0.260659
income,0.109383,0.211275,0.132807,1.000000,0.141241,0.345161,-0.010741,-0.090790
ed,-0.070503,-0.071509,-0.145550,0.141241,1.000000,-0.213886,0.488041,0.216112
employ,0.445755,0.622553,0.520926,0.345161,-0.213886,1.000000,-0.174470,-0.337969
equip,-0.117102,-0.071357,-0.148977,-0.010741,0.488041,-0.174470,1.000000,0.275284
churn,-0.376860,-0.287697,-0.260659,-0.090790,0.216112,-0.337969,0.275284,1.000000

In [6]:
ind_var = np.asarray(telecom_data[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
ind_var[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [7]:
dep_var = np.asarray(telecom_data[['churn']].values.ravel())
dep_var[0:5]

array([1, 1, 0, 0, 0])

In [8]:
ind_norm = StandardScaler().fit(ind_var).transform(ind_var)
ind_norm[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [9]:
train_ind, test_ind, train_dep, test_dep = train_test_split(ind_norm, dep_var, test_size=0.2, random_state=42)

In [10]:
LogisticRegression = linear_model.LogisticRegression()
LogR = LogisticRegression.fit(train_ind, train_dep)
pred_dep = LogR.predict(test_ind)
pred_dep[11:21]

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [11]:
prob_dep = LogR.predict_proba(test_ind)
prob_dep[11:21]

array([[0.93452287, 0.06547713],
       [0.81228705, 0.18771295],
       [0.96519565, 0.03480435],
       [0.44952535, 0.55047465],
       [0.90271205, 0.09728795],
       [0.63185714, 0.36814286],
       [0.4722927 , 0.5277073 ],
       [0.7179757 , 0.2820243 ],
       [0.63303886, 0.36696114],
       [0.95207769, 0.04792231]])

In [12]:
test_dep[11:21]

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [ ]:
coef = pd.Series(LogR.coef_[0], index= telecom_data.columns[:-1])
coef.sort_values().plot(kind='barh')
plt.title("Feature Coefficients in Logistic Regression Churn Model")
plt.xlabel("Coefficient Value")
plt.show()

In [ ]:
log_loss(test_dep, prob_dep)